# Generated by Django 5.0.6 on 2024-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='alert_quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
