# Generated by Django 5.0.6 on 2024-06-29 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_branch_logo'),
        ('inventory', '0002_inventory_alert_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='branch'),
        ),
    ]
