# Generated by Django 5.2.3 on 2025-06-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
