# Generated by Django 5.2.3 on 2025-06-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_date_added_inventory_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='date_modified',
            new_name='updated_at',
        ),
    ]
