# Generated by Django 5.0.14 on 2025-07-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_branch_email'),
        ('inventory', '0007_inventory_available_quantity_inventory_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.branch', verbose_name='branch'),
        ),
    ]
