# Generated by Django 5.0.14 on 2025-07-13 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_branch_email'),
        ('inventory', '0008_alter_inventory_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='branch'),
        ),
    ]
