# Generated by Django 5.0.6 on 2024-05-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options'),
        ('sales', '0019_alter_sale_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
            options={
                'verbose_name': 'Product Sale Report',
                'verbose_name_plural': 'Product Sale Reports',
                'db_table': 'ProductSaleReports',
            },
        ),
    ]
