# Generated by Django 5.0.6 on 2024-07-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSaleReport',
        ),
    ]
