# Generated by Django 5.0.14 on 2025-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_permission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/img/profile/user-1.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
