# Generated by Django 5.0.14 on 2025-07-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_number',
        ),
    ]
