# Generated by Django 5.2.3 on 2025-06-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
