# Generated by Django 5.2.3 on 2025-06-29 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_date_modified_expense_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
