# Generated by Django 5.0.6 on 2024-06-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
    ]
