# Generated by Django 5.0.2 on 2024-03-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='id',
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
