# Generated by Django 5.0.2 on 2024-05-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_license_id_alter_license_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='license',
            table='Licenses',
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='Notifications',
        ),
    ]
