# Generated by Django 5.0 on 2024-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
                ('countryCode', models.CharField(max_length=10, unique=True)),
                ('countryName', models.CharField(max_length=100, unique=True)),
                ('currencyCode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('noticeNumber', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('noticeURL', models.URLField()),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('taxTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('taxTypeName', models.CharField(max_length=100)),
                ('taxTypeRate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxTypeIdentifier', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'TaxType',
                'verbose_name_plural': 'TaxTypes',
                'db_table': 'TaxType',
            },
        ),
    ]
