# Generated by Django 5.0.2 on 2024-05-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
                ('countryCode', models.CharField(max_length=10, unique=True)),
                ('countryName', models.CharField(max_length=100, unique=True)),
                ('currencyCode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='EtimsBranch',
            fields=[
                ('branch_tin', models.CharField(max_length=11)),
                ('branch_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_status_code', models.CharField(max_length=10)),
                ('province_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sctr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Etims Branch',
                'verbose_name_plural': 'Etims Branches',
                'db_table': 'EtimsBranch',
            },
        ),
        migrations.CreateModel(
            name='EtimsNotice',
            fields=[
                ('noticeNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('noticeUrl', models.URLField()),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('registrarName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='PackagingUnits',
            fields=[
                ('packagingUnitId', models.AutoField(primary_key=True, serialize=False)),
                ('packagingUnitName', models.CharField(max_length=100)),
                ('packagingUnitDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Packaging Unit',
                'verbose_name_plural': 'Packaging Units',
                'db_table': 'PackagingUnits',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('taxTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('taxTypeName', models.CharField(max_length=100)),
                ('taxTypeRate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxTypeIdentifier', models.CharField(max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'TaxType',
                'verbose_name_plural': 'TaxTypes',
                'db_table': 'TaxType',
            },
        ),
        migrations.CreateModel(
            name='UnitOfQuantity',
            fields=[
                ('unitOfQuantityId', models.AutoField(primary_key=True, serialize=False)),
                ('unitOfQuantityName', models.CharField(max_length=100)),
                ('unitOfQuantityDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unit Of Quantity',
                'verbose_name_plural': 'Units Of Quantity',
                'db_table': 'UnitsOfQuantity',
            },
        ),
        migrations.CreateModel(
            name='ItemClassCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemClassLevel', models.IntegerField()),
                ('itemClassCodeName', models.CharField(max_length=100, unique=True)),
                ('useYN', models.BooleanField(default=True)),
                ('taxType', models.ForeignKey(db_column='taxType', on_delete=django.db.models.deletion.PROTECT, to='etims.taxtype')),
            ],
            options={
                'verbose_name': 'Item Class Code',
                'verbose_name_plural': 'Item Class Codes',
                'db_table': 'ItemClassCodes',
            },
        ),
    ]
