# Generated by Django 5.0.2 on 2024-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemclasscodes',
            name='taxType',
        ),
        migrations.AddField(
            model_name='itemclasscodes',
            name='majorTargetYN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemclasscodes',
            name='taxTypeCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
