# Generated by Django 5.0 on 2024-03-02 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingUnits',
            fields=[
                ('packagingUnitId', models.AutoField(primary_key=True, serialize=False)),
                ('packagingUnitName', models.CharField(max_length=100)),
                ('packagingUnitDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Packaging Unit',
                'verbose_name_plural': 'Packaging Units',
                'db_table': 'PackagingUnits',
            },
        ),
        migrations.CreateModel(
            name='UnitOfQuantity',
            fields=[
                ('unitOfQuantityId', models.AutoField(primary_key=True, serialize=False)),
                ('unitOfQuantityName', models.CharField(max_length=100)),
                ('unitOfQuantityDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unit Of Quantity',
                'verbose_name_plural': 'Unit Of Quantity',
                'db_table': 'UnitsOfQuantity',
            },
        ),
        migrations.CreateModel(
            name='ItemClassCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemClassLevel', models.IntegerField()),
                ('itemClassCodeName', models.CharField(max_length=100, unique=True)),
                ('useYN', models.BooleanField(default=True)),
                ('taxType', models.ForeignKey(db_column='taxType', on_delete=django.db.models.deletion.PROTECT, to='etims.taxtype')),
            ],
            options={
                'verbose_name': 'Item Class Code',
                'verbose_name_plural': 'Item Class Codes',
                'db_table': 'ItemClassCodes',
            },
        ),
    ]
