# Generated by Django 5.0.2 on 2024-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0002_remove_itemclasscodes_taxtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclasscodes',
            name='itemClassCode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
