# Generated by Django 5.0.2 on 2024-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0003_itemclasscodes_itemclasscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclasscodes',
            name='itemClassCode',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='itemclasscodes',
            name='itemClassCodeName',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='itemclasscodes',
            name='taxTypeCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
