# Generated by Django 5.0.2 on 2024-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0004_alter_itemclasscodes_itemclasscode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclasscodes',
            name='itemClassCodeName',
            field=models.CharField(max_length=1000),
        ),
    ]
