# Generated by Django 5.0.2 on 2024-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0006_etimsproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxtype',
            name='taxTypeId',
        ),
        migrations.RemoveField(
            model_name='taxtype',
            name='taxTypeIdentifier',
        ),
        migrations.RemoveField(
            model_name='taxtype',
            name='taxTypeRate',
        ),
        migrations.AddField(
            model_name='packagingunits',
            name='code',
            field=models.CharField(default='BZ', max_length=5),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxtype',
            name='taxTypeCode',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxtype',
            name='taxTypeDescription',
            field=models.CharField(default='A-Exempt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofquantity',
            name='code',
            field=models.CharField(default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='taxTypeName',
            field=models.CharField(max_length=20),
        ),
    ]
