# Generated by Django 5.0.2 on 2024-05-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0007_remove_taxtype_taxtypeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='taxTypeCode',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
