# Generated by Django 5.0.6 on 2024-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etims', '0008_remove_taxtype_id_alter_taxtype_taxtypecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='id',
            field=models.BigAutoField(auto_created=True, default='A', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='taxTypeCode',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
