# Generated by Django 5.0.6 on 2024-06-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=100, verbose_name='Status of the category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=256)),
                ('track_inventory', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=100, null=True, verbose_name='Status of the product')),
                ('price', models.FloatField(default=0)),
                ('country_of_origin', models.CharField(blank=True, max_length=5, null=True)),
                ('product_type', models.CharField(choices=[('1', 'Raw Material'), ('2', 'Finished Product'), ('3', 'Service without stock')], default='Finished Product', max_length=30, verbose_name='Product Type')),
                ('packaging_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
