# Generated by Django 5.0.6 on 2024-06-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0002_supplier_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supllier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='supplier'),
        ),
    ]
