# Generated by Django 5.0.6 on 2024-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_supllier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/defaults/default.png', null=True, upload_to='products'),
        ),
    ]
