# Generated by Django 5.0.6 on 2024-07-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supllier',
            new_name='supplier',
        ),
    ]
