# Generated by Django 5.0.2 on 2024-03-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_track_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_category', 'Can view category'), ('can_add_category', 'Can add category'), ('can_edit_category', 'Can edit category'), ('can_delete_category', 'Can delete category')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product', 'Can view product'), ('can_add_product', 'Can add product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
