# Generated by Django 5.2.3 on 2025-06-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='display_image',
        ),
    ]
