# Generated by Django 5.2.3 on 2025-06-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_image_product_display_image'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='product_photos', to='utils.photo', verbose_name='Product Photos'),
        ),
    ]
