# Generated by Django 5.0.2 on 2024-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Raw Material'), ('2', 'Finished Product'), ('3', 'Service without stock')], default='Finished Product', max_length=30, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=100, null=True, verbose_name='Status of the product'),
        ),
    ]
