# Generated by Django 5.0.14 on 2025-07-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tax_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Tax Group',
                'verbose_name_plural': 'Tax Groups',
                'db_table': 'TaxGroup',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_group', to='products.taxgroup'),
        ),
    ]
