# Generated by Django 5.0.14 on 2025-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxgroup',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=100, verbose_name='Status of the tax group'),
        ),
    ]
