services:
  # PostgreSQL Database
  db:
    image: postgres:16.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .docker.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application
  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .docker.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      bash -c "python manage.py migrate &&  
              python manage.py createsuperuser --noinput &&             
               python manage.py collectstatic --no-input &&
               gunicorn django_pos.wsgi:application --bind 0.0.0.0:8000"

  # Nginx for serving static files and as reverse proxy
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
