# Generated by Django 5.0.14 on 2025-07-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseData',
        ),
    ]
