# Generated by Django 5.2.3 on 2025-06-28 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(db_column='sale', default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
    ]
