# Generated by Django 5.0 on 2024-01-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("sales", "0003_rename_venta_saledetail_sale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                db_column="customer",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="customers.customer",
            ),
        ),
    ]
