# Generated by Django 5.0.14 on 2025-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
        ('sales', '0003_saleitem_sale_delete_saledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.ManyToManyField(blank=True, db_constraint=False, db_table='SalePayments', related_name='sales', to='payments.payment', verbose_name='Payments'),
        ),
    ]
