# Generated by Django 5.0.14 on 2025-07-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
