# Generated by Django 5.0 on 2024-02-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_customer_alter_saledetail_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'Sale Detail', 'verbose_name_plural': 'Sale Details'},
        ),
    ]
