# Generated by Django 5.0.14 on 2025-07-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount_change',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_payed',
        ),
    ]
