# Generated by Django 5.0.14 on 2025-07-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_amount_change_remove_sale_amount_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment',
        ),
    ]
