# Generated by Django 5.0.14 on 2025-07-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sale_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
    ]
