# Generated by Django 5.0.2 on 2024-03-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_track_inventory'),
        ('sales', '0009_delete_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={},
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='total_detail',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='products',
            field=models.ManyToManyField(db_column='products', to='products.product'),
        ),
        migrations.AlterModelTable(
            name='saledetail',
            table=None,
        ),
    ]
