# Generated by Django 5.0.14 on 2025-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_sale_tax_amount_remove_sale_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(blank=True, to='sales.saleitem'),
        ),
    ]
