# Generated by Django 5.0.2 on 2024-03-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_saledetail_options_remove_saledetail_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'SaleDetail', 'verbose_name_plural': 'SaleDetails'},
        ),
        migrations.AlterModelTable(
            name='saledetail',
            table='SaleDetails',
        ),
    ]
