# Generated by Django 5.0.2 on 2024-03-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_track_inventory'),
        ('sales', '0011_alter_saledetail_options_alter_saledetail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='products',
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'SaleItem',
                'verbose_name_plural': 'SaleItems',
                'db_table': 'SaleItems',
            },
        ),
        migrations.AddField(
            model_name='saledetail',
            name='items',
            field=models.ManyToManyField(db_column='items', to='sales.saleitem'),
        ),
    ]
