# Generated by Django 5.0.2 on 2024-03-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_saledetail_products_saleitem_saledetail_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
