# Generated by Django 5.0.2 on 2024-03-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options'),
        ('sales', '0015_alter_saledetail_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
