# Generated by Django 5.0.2 on 2024-03-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_saledetail_sale_alter_saleitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('print_sale_receipt', 'Can print receipt'), ('view_sale_record', 'Can view sale'), ('add_sale_record', 'Can add sale'), ('edit_sale_record', 'Can edit sale'), ('delete_sale_record', 'Can delete sale')], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
