# Generated by Django 5.0.6 on 2024-05-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
