# Generated by Django 5.0.2 on 2024-05-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_sale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
