# Generated by Django 5.0.14 on 2025-07-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
