# Generated by Django 5.0.6 on 2024-06-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
