# Generated by Django 5.0.14 on 2025-06-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplier_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='kra_pin',
            new_name='tax_id',
        ),
    ]
