# Generated by Django 5.0.14 on 2025-07-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_rename_kra_pin_supplier_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
