# Generated by Django 5.0.6 on 2024-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.TextField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('kra_pin', models.CharField(blank=True, default='A000000000Z', max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.FileField(blank=True, default='/img/undraw_profile.svg', null=True, upload_to='customers')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
            },
        ),
    ]
