# Generated by Django 5.0 on 2024-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="kra_pin",
            field=models.CharField(default="A000000000Z", max_length=12),
        ),
    ]
