# Generated by Django 5.0.14 on 2025-06-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='kra_pin',
            new_name='tax_number',
        ),
    ]
