# Generated by Django 5.0.2 on 2024-03-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_is_active_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='/img/default.png', null=True, upload_to='customers'),
        ),
    ]
