# Generated by Django 5.0.2 on 2024-03-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.FileField(blank=True, default='/img/undraw_profile.svg', null=True, upload_to='customers'),
        ),
    ]
