# Generated by Django 5.0 on 2024-01-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="")),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
    ]
