# Generated by Django 5.0 on 2024-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency_symbol",
            field=models.CharField(default="Kshs", max_length=5),
        ),
    ]
