# Generated by Django 5.0 on 2024-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_currency_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(default='Kes', max_length=5),
        ),
    ]
