# Generated by Django 5.0.6 on 2024-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_headquarter',
            field=models.BooleanField(default=False),
        ),
    ]
