# Generated by Django 5.0 on 2024-02-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_alter_company_currency_symbol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
