# Generated by Django 5.0.6 on 2024-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_branch_address_alter_branch_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to=''),
        ),
    ]
