# Generated by Django 5.0 on 2024-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_template_id',
            field=models.IntegerField(default=1),
        ),
    ]
