# Generated by Django 5.0.6 on 2024-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_branch_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
