# Generated by Django 5.0 on 2024-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_invoice_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bill_template_id',
            field=models.IntegerField(default=1),
        ),
    ]
