# Generated by Django 5.0.2 on 2024-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
