# Generated by Django 5.2.3 on 2025-06-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='kra_pin',
            new_name='tax_registration_number',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
