# Generated by Django 5.0.2 on 2024-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_kra_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to=''),
        ),
    ]
