# Generated by Django 5.0.14 on 2025-07-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_kra_pin_company_tax_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
    ]
