# Generated by Django 5.0.14 on 2025-07-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_branch_branch_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'branch_name')},
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_headquarter', True)), fields=('company', 'is_headquarter'), name='unique_headquarter'),
        ),
    ]
