name: Ultimate POS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_NAME: "verceldb"
  DATABASE_USER: "default"
  DATABASE_PASSWORD: "3dzgrJBoAk8Y"
  DATABASE_HOST: "ep-winter-bonus-a4826y7y-pooler.us-east-1.aws.neon.tech"
  DATABASE_PORT : 5432	
  DJANGO_SECRET_KEY: "django-insecure-shfzstshi=+%g-@_=nc4_x=9xdpt1thdo=^k#($km%htb-se)("

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r django_pos/requirements.txt
    - name: Run Tests
      run: |
        python django_pos/manage.py test
    - name: Run Checks
      run: |
        python django_pos/manage.py check
